baseurl = "http://scribe.webbucket.io/"
languageCode = "en-us"
title = "Scribe"
theme = "purehugo"
Paginate = 10
disqusShortname = "webbucket-scribe"

[params]
  twitterName = "jaybeecave"
  githubName = "jaybeecave"
  description = "Brain's overloaded.... uploading here!"
  google_analytics = "UA-85435316-1"